// let b = 32;

try {
  let a = 2 + b;
} catch (error) {
  console.log(error);
} finally {
  console.log("Executou");
}
